In [4]:

import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個

array([50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 86,  83,  84,  70,  58],
       [ 82,  58,  65,  98,  68],
       [ 94,  72,  99,  57,  79],
       [ 68,  61,  73,  68,  84],
       [ 97,  75,  55,  82,  97],
       [ 88,  72,  92,  57,  77],
       [ 88,  62,  61,  83,  94],
       [ 74,  99,  92,  98,  90],
       [ 82,  80,  72,  57, 100],
       [ 74, 100,  52,  64,  57],
       [ 97,  61,  73,  80,  89],
       [ 61,  50,  75,  88, 100],
       [ 65,  67,  69,  95,  72],
       [ 62,  65,  68,  80,  70],
       [ 71,  81,  83,  84,  52],
       [ 61,  92,  84,  65,  87],
       [ 88,  55,  52,  63,  63],
       [ 84,  84,  70,  76,  69],
       [ 67,  84,  89,  67,  80],
       [ 59,  92,  79,  94,  91],
       [ 62,  96,  93,  97,  98],
       [ 85,  95, 100,  60,  65],
       [ 53,  74,  66,  65,  68],
       [ 80,  51,  75,  98,  51],
       [ 66,  92,  93,  62,  68],
       [ 67,  74,  88,  87,  94],
       [ 82,  64,  89,  68,  89],
       [ 88,  61,  89,  87,  68],
       [ 79,  76,  70,  85,  93],
       [ 61,  

In [7]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[86, 83, 84, 70, 58]], dtype=int32)

In [8]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[86, 83, 84],
       [82, 58, 65],
       [94, 72, 99],
       [68, 61, 73],
       [97, 75, 55]], dtype=int32)

In [9]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 84,  65,  99,  73,  55,  92,  61,  92,  72,  52,  73,  75,  69,
        68,  83,  84,  52,  70,  89,  79,  93, 100,  66,  75,  93,  88,
        89,  89,  70,  95,  69,  95,  67,  61,  94,  63,  75,  81,  81,
        70,  69,  70,  85,  78,  71,  71,  73,  70,  64,  69], dtype=int32)

In [10]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([381, 371, 401, 354, 406, 386, 388, 453, 391, 347, 400, 374, 368,
       345, 371, 389, 321, 383, 387, 415, 446, 405, 326, 355, 381, 410,
       392, 393, 403, 393, 314, 393, 396, 340, 349, 339, 394, 371, 369,
       331, 389, 350, 353, 413, 332, 367, 437, 372, 345, 411], dtype=int32)

In [11]:
total / 5

array([76.2, 74.2, 80.2, 70.8, 81.2, 77.2, 77.6, 90.6, 78.2, 69.4, 80. ,
       74.8, 73.6, 69. , 74.2, 77.8, 64.2, 76.6, 77.4, 83. , 89.2, 81. ,
       65.2, 71. , 76.2, 82. , 78.4, 78.6, 80.6, 78.6, 62.8, 78.6, 79.2,
       68. , 69.8, 67.8, 78.8, 74.2, 73.8, 66.2, 77.8, 70. , 70.6, 82.6,
       66.4, 73.4, 87.4, 74.4, 69. , 82.2])

In [12]:

#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([76.2, 74.2, 80.2, 70.8, 81.2, 77.2, 77.6, 90.6, 78.2, 69.4, 80. ,
       74.8, 73.6, 69. , 74.2, 77.8, 64.2, 76.6, 77.4, 83. , 89.2, 81. ,
       65.2, 71. , 76.2, 82. , 78.4, 78.6, 80.6, 78.6, 62.8, 78.6, 79.2,
       68. , 69.8, 67.8, 78.8, 74.2, 73.8, 66.2, 77.8, 70. , 70.6, 82.6,
       66.4, 73.4, 87.4, 74.4, 69. , 82.2])

In [13]:

#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([76.2, 74.2, 80.2, 70.8, 81.2, 77.2, 77.6, 90.6, 78.2, 69.4, 80. ,
       74.8, 73.6, 69. , 74.2, 77.8, 64.2, 76.6, 77.4, 83. , 89.2, 81. ,
       65.2, 71. , 76.2, 82. , 78.4, 78.6, 80.6, 78.6, 62.8, 78.6, 79.2,
       68. , 69.8, 67.8, 78.8, 74.2, 73.8, 66.2, 77.8, 70. , 70.6, 82.6,
       66.4, 73.4, 87.4, 74.4, 69. , 82.2])