In [10]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [9]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4 , 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [8]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [11]:
np.random.rand()
np.random.rand(30, 4)

array([[0.567515  , 0.09895459, 0.09888513, 0.99903415],
       [0.27919526, 0.71049478, 0.35365739, 0.96727349],
       [0.08298054, 0.82342665, 0.53687742, 0.2267248 ],
       [0.26075599, 0.7041407 , 0.15435507, 0.81038957],
       [0.09537877, 0.68398775, 0.32508418, 0.88464354],
       [0.34779551, 0.20310346, 0.98027595, 0.90895052],
       [0.99516287, 0.2399113 , 0.95057511, 0.18942375],
       [0.23195703, 0.57485828, 0.7244708 , 0.60030642],
       [0.95916703, 0.09706208, 0.66748641, 0.72946642],
       [0.96702303, 0.20841153, 0.4702149 , 0.37177351],
       [0.37911268, 0.74905394, 0.07011723, 0.20603663],
       [0.58340192, 0.52403744, 0.82879859, 0.39113469],
       [0.07384253, 0.17678188, 0.11600699, 0.29001388],
       [0.96848405, 0.57993138, 0.66424292, 0.84327713],
       [0.19135385, 0.85933827, 0.62204584, 0.97105002],
       [0.70242587, 0.9940329 , 0.12166188, 0.66830676],
       [0.41940542, 0.48442558, 0.01047965, 0.27175434],
       [0.98881614, 0.08049901,

In [12]:

scores = np.random.randint(50, 101,size=(50,5))
scores

array([[ 69,  92,  86,  96, 100],
       [ 77,  93,  86,  81,  87],
       [ 64,  51,  97,  63,  73],
       [ 99,  64,  74,  81,  68],
       [ 69,  90,  53,  59,  61],
       [ 94,  82,  96,  80,  77],
       [ 65,  78,  70,  87,  62],
       [ 81,  94,  74,  52,  87],
       [ 59,  92,  83,  59, 100],
       [ 96,  67,  79,  93,  71],
       [ 79,  57,  94,  85,  97],
       [ 90,  87,  96,  81,  65],
       [ 94,  94,  67,  50,  95],
       [ 87,  52,  50,  89,  54],
       [ 92,  67,  68,  69,  93],
       [ 67,  77,  99,  73,  65],
       [ 93,  70,  68,  79,  56],
       [ 61,  77,  61,  52,  54],
       [ 72,  53,  61,  93,  84],
       [ 92,  67,  68,  79,  69],
       [ 75,  78,  70,  87,  50],
       [ 62,  65,  97,  77,  59],
       [ 61,  69,  73,  91,  61],
       [ 78,  91,  69,  98,  74],
       [ 51,  93,  60, 100,  69],
       [ 79,  85,  52,  70,  76],
       [ 79,  90,  65, 100,  96],
       [ 82,  94,  87,  82,  72],
       [ 66,  94,  82,  98,  79],
       [ 99,  